name: duck_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dotenv: ^4.2.0
  drift: ^2.30.0
  drift_postgres: ^1.3.1
  postgres: ^3.5.9

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_lint: ^0.1.0
  drift_dev: ^2.30.0
  mocktail: ^1.0.3
  test: ^1.25.5
